### PR TITLE
NightMode Styling

### PR DESCRIPTION
**Pull request by jeprecated**
Anki 2.1.20 recently added a native NightMode setting in the config. It works by automatically inveryting most colors, however it seems to not work for specifically set rgba values, tho it provides a ".nightMode" override for the css to handle things like that. 

This PR contains the styling necessary to have all things be visible in that mode. I tweeked the alpha variables a bit to what looks good to me personally, feel free to change it of course 👍

### CODE REVIEW

**Comment by remiberthoz** [comment]
Hey!

Thank you for this pull request. Night mode is a feature other people have been asking and because I don't use it myself, I haven't put a lot of attention to it...

If I may suggest, I would change the card's background from pure back to a dark grey like `rgba(33, 33, 33, 1)`. Similarly, the card's headers (css `box_title`) currently have a light colour, I would rather transform that to a darker shade so that the text can be in white. The original "day mode" theme was based on Google's Material Design [colour palette](https://material.io/resources/color/#!/?view.left=0&view.right=0), it would be nice to ride along the trend and pick colours from there!

If you don't mind doing it, I'll wait for new commits on the pull request.

Thank you again for the implementation.

**Comment by jeprecated** [comment]
Alright here you go, how does this look?

image

I applied the grey background, and changed the colour of box_title, as requested. Box_Title cannot be *too dark* though as most of the images use black as their line colour of choice (see the above pic of Protactinium as an example). It's dark enough to allow for white text though, so I think it's good enough 👍

**Comment by remiberthoz** [comment]
Wow that's nice! Thank you very much! I'll of merge and publish over the weekend.

**Comment by remiberthoz** [comment]
Hey! Sorry for the delay. The PR is now merged and changes are reflected in version 2.3.0, released to [AnkiWeb](https://ankiweb.net/shared/info/490209917)!

Thank you :smiley:

**Pull request merged**
