### PR TITLE
Cards for 108-112 and 114-118

### PR DESCRIPTION
**Pull request by RandomQuetzalcoatl**
Been using this deck for years, and finally got tired of saying I have 107 elements memorized instead of the entire periodic table. I made cards for the remaining elements and they already have phrases and 32x32 pixel art without a background. Each image has a number in it, some more obvious than others. Most of the phrases are made up, except for Yuri Oganesson, which is technically true because he's written over 300 scientific papers, which is more than 118.

### CODE REVIEW

**Comment by RandomQuetzalcoatl** [comment]
Phrases and Images for easy review:
David **H**a**s**selhoff will live to 108 and his movies are great.
108hassium

The **m**igh**t**y man could lift 109 pounds and climb **m**oun**t**ains.
109meitnerium

The Nintendo **DS** battery lasts 110 hours while playing Pokemon Stadium.
110darmstadtium

**C**oper**n**icus's favorite of the 12 zodiac signs was the constellation Capricorn.
112copernicium

A 114-pound bird **Fl**ew over the tree.
114flerovium

**M**oscow **c**astle has 115 flags. The tsar plays Minecraft.
115moscovium

If you **L**o**v**e your liver, don't drink 116 ounces of alcohol at once.
116livermorium

The 117th **T**ennis tournament was the best ever **s**een.
117tennessine

Yuri **Og**anesson has published more than 118 scientific papers.
118oganesson

**Comment by horwitz** [comment]
some really good stuff here (and I'm excited that we'll likely have a full deck soon)—thanks!
a few notes:

108: "108, and" -> "108 and"

109: "lbs" -> "lbs."; any chance for a "9" on the bicep (instead of "10"—maybe I'm missing something (I probably am!), but why is there a "10" there)?

110: "pokemon stadium" -> "Pokémon Stadium"; maybe have someone play with all 10 fingers (with an implicit +100 to give 110)—if not in the image, at least in the text?

112: there are 88 constellations (making looking at 113 impossible) (also, I'm not sure whether to read this as Cn = 112 or Cn = (112+1=)113)

115: "Czar" -> "tsar" (spelling and case)

117: "Tournament" -> "tournament"

**Comment by horwitz** [comment]
112: still along the lines of the Capricorn idea (but instead of 112/113 constellations)—maybe something about it being one of the 12 signs of the (Western) zodiac (and then "12" cues "112")?

**Comment by RandomQuetzalcoatl** [comment]
Made the spelling corrections for 108, 115, and 117. Replaced lbs with pounds in case someone is unfamiliar with the imperial system abbreviation. The nine for 109 is supposed to be the arm with the weight, considered moving the weight further back to make it more straightforward but looked a bit wonky. You raise a great point for 112, alternatively "Copernicus' favorite constellation was **C**apricorn, he would look at the 12 zodiacs every **n**ight"

**Comment by horwitz** [comment]
109: I can totally see the arm+weight = "9" now that you mention it—cute (and helpful)!

112: perhaps something like "*C*oper*n*icus's favorite of the 12 zodiac signs was the *c*o*n*stellation *C*apricor*n*"? (FWIW, I think "zodiac" (in terms of the Western zodiac) refers (essentially) to the collection of the 12 signs, not to an individual sign) (the "the *c*o*n*stellation" part could be removed, too—it's perhaps a bit much?)

**Comment by RandomQuetzalcoatl** [comment]
Like the rewording and changed 112, which leaves 110. I was going for "The Nintendo DS battery last 110 hours while playing Pokemon Stadium." With a battery and 110 on the lower part of the screen. I could try to do fingers, but it would be very difficult with the limited resolution. Admittedly 110 hours is a lot, so it could be minutes instead.

**Comment by horwitz** [comment]
110: makes sense re resolution, maybe something about all 10 fingers hurting after playing for 110 hours? (or drop the fingers thing altogether :) ) (re hours vs. minutes: it's certainly a matter of opinion, though I like hours there—it's more ridiculous and (arguably) thus more memorable) and, frankly, what you suggest re battery seems fine too

**Comment by remiberthoz** [comment]
Hi, thanks a lot both of you! I'll review and merge tomorrow.

**Comment by remiberthoz** [comment]
Merged and updated ! Thanks a lot @RandomQuetzalcoatl  for putting the effort of preparing a complete pull request with pictures :tada:. Many thanks to @horwitz for the instant feedback :+1:.

I updated the deck on AnkiWeb already, but if you two want to suggest minor adjustments, feel free to continue discussing here!

**Comment by jeprecated** [comment]
image

**Pull request merged**
