### PR TITLE
Added memory pegs for Bohrium and Nihonium, but missing images

### PR DESCRIPTION
**Pull request by Lykos**
The cards are still missing images and I am not 100% sure the guids are correct.

I don't know how 100% guids work, it says in the documentation it's a random string of length 10. So I took the union of all characters appearing in other guids and created a string of length 10 based on those characters. Not sure whether this is correct.

It seems you are pretty efficient at creating those images while it would take me forever to figure out how to do it.

If this is no help at all, feel free to reject. If you like the memory pegs, take it and complete it.

### CODE REVIEW

**Comment by remiberthoz** [comment]
Hey, thank you for contributing :tada: !

You did well with the guids, as you said they only have to be a random, unique, string of characters. As for the pictures, I create them as 32x32 pixels gif files in gimp. I can illustrate Bohrium and Niohnium to match the pegs you proposed.

I will be very happy to merge the changes. For consistency of the git history, may I ask you to:
- change the destination branch of the pull request to `develop`
- revert the changes you made to `version.txt` (this file is modified just before the releases, when everything is ready)

**Comment by Lykos** [comment]
Ok, thanks. I am at work now, will do when I get home.

**Comment by Lykos** [comment]
Done

**Comment by remiberthoz** [comment]
Perfect, thank you !

**Comment by remiberthoz** [comment]
Changes in this PR close #110 and #116

**Comment by Lykos** [comment]
I have memory pegs for the remaining ones, too, but they are all in German.

They work super nice in German. E.g. Bohrium sounds like "drill" and 7
sounds like "use a sieve", so 107 is actually that someone drills and the
dust from that gets put into a sieve. "Hassium" sounds like "Haselnuss"
which is "hazelnut" or "hassen" which is "to hate" and "8" sounds like
"attention", so there are some obvious things of paying attention about the
hazelnut hater.

**Comment by remiberthoz** [comment]
The pull request is now merged into the master branch, and released with version `v2.2.0`! Thanks for contributing!

**Pull request merged**
